# Generated by Django 4.0.3 on 2024-06-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionOpsations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condition', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipOpsations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateOwnerShipDeatils',
            fields=[
                ('PvOwnerShip_QrCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreeImages', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreeName', models.CharField(max_length=50)),
                ('BotanicalName', models.CharField(max_length=50)),
                ('Family', models.CharField(max_length=50)),
                ('FlowerColor', models.CharField(max_length=20)),
                ('FruitSeason', models.CharField(max_length=20)),
                ('FlowerSeason', models.CharField(max_length=20)),
                ('ShortDescription', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeData',
            fields=[
                ('QrCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Girth_m', models.IntegerField()),
                ('Height_m', models.IntegerField()),
                ('Age_y', models.IntegerField()),
                ('TreeCanopy_m', models.IntegerField()),
                ('Location_Lat', models.CharField(max_length=20)),
                ('Location_Long', models.CharField(max_length=20)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ConditionInfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ConditionBy', to='api.conditionopsations')),
                ('TreeImage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TreeImageUriBy', to='api.treeimage')),
                ('TreeInfo_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TreeInfoBy', to='api.treeinfo')),
                ('ownershipinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnershipBy', to='api.ownershipopsations')),
            ],
        ),
    ]
